name: Create Release

# Ce workflow est déclenché lorsqu'un nouveau tag est poussé
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Utilise le tag poussé comme version
          name: Release ${{ github.ref_name }}  # Nom de la release
          body: |
            Release Notes:
            - Cette version contient les modifications apportées jusqu'à ce tag.
          draft: false  # Si tu veux créer une version brouillon, définis comme true
          prerelease: false  # Si c'est une version préliminaire, définis comme true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Jeton GitHub pour l'authentification
